<?php

namespace api\controllers;

use api\components\BaseController;
use yii\db\ActiveRecord;

class PhotoAlarmController extends BaseController
{
    /** @var ActiveRecord $modelClass */
    public $modelClass = PhotoAlarmController::class;

    public function actionCreate()
    {
        return parent::actionCreate(); // TODO: Change the autogenerated stub
    }
}
